include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    unused_element: false
    dead_code: false
    dead_null_aware_expression: false
    unrelated_type_equality_checks: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    unrelated_type_equality_checks: warning