name: dairy_manager
description: A new Flutter project.

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  pdf: ^3.11.3           # updated to latest stable
  printing: ^5.10.0      # updated to latest stable
  intl: ^0.20.2
  share_plus: ^12.0.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  reorderable_grid_view: ^2.2.8
  open_filex: ^4.0.5
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.1.1
  device_info_plus: ^9.1.1
  archive: ^3.4.9
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   # - assets/images/logo.png   # apna company logo
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/OpenSans-Regular.ttf
    - assets/fonts/OpenSans-Bold.ttf
