name: dairy_manager
description: A new Flutter project.

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  pdf: ^3.10.7
  printing: ^5.12.0
  intl: ^0.20.2
  share_plus: ^7.2.1
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  reorderable_grid_view: ^2.2.8
  open_filex: ^4.0.5
  connectivity_plus: ^6.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
